### ISSUE TITLE
Provide the same results regardless of capitalization 

### ISSUE THREAD

**Issue by sfolsom** [LD4P/qa_server#232] opened 2019-11-01 12:41 UTC
For tracking purposes, please create a separate issue for each indexing improvement request.

- [ ] Please describe the expected performance and accuracy of a particular vocabulary. 

https://lookup.ld4l.org/authorities/search/linked_data/locnames_ld4l_cache?q=university%20of%20pennsylvania&maxRecords=4&context=true

https://lookup.ld4l.org/authorities/search/linked_data/locnames_ld4l_cache?q=University%20of%20Pennsylvania&maxRecords=4&context=true

- [ ] If applicable, please update and provide links related to existing tests, e.g. https://github.com/LD4P/qa_server/tree/master/lib/generators/qa_server/templates/config/authorities/linked_data/scenarios
- [ ] If applicable, please update the relevant tab in https://docs.google.com/spreadsheets/d/1rPvEoP9iYNkxJ0eWC8gXe3ci7e6mhW0da59xkGhadi0/edit?usp=sharing for the particular dataset in question

**Comment by elrayle** [comment] 2019-11-04 20:00
@sfolsom This looks like a duplicate of Issue #133.  Perhaps we can move your example over to that issue and close this one.

**Closed** 2019-11-15 20:33 UTC
Labels: Indexing, duplicate
