### ISSUE TITLE
LC Code List for Cultural Heritage Organizations

### ISSUE THREAD

**Issue by bushmanb** [LD4P/qa_server#175] opened 2019-09-10 17:29 UTC
_Please only use this issue template for LD4P2 requests for a new data source to be added to QA. If your requesting changes to how a dataset currently available in QA is treated, please use the indexing bug issue template._

__For LD4P2 partners and cohorts:__

I had reported a bug in Sinopia linked data editor testing and they said to submit it here.  https://id.loc.gov/vocabulary/organizations  needs to be available so we associate resources with institutions.

**Comment by michelleif** [comment] 2019-09-15 16:36
from @kirkhess via email 8/20/19 "The org code list has some issues – in general, I think the problem is everyone has a code they use today and have no idea the label to use for the code. The labels have a very tenuous connection to the code plus all the old codes are never deprecated or removed – there 40+ LC codes of which we use 1 (DLC). We were trying to change the suggest service to allow you to type in the code instead of the name. I think we need to work this issue to fix the list itself as well. A QA list isn’t going to fix this code/label + obsolete code problem."

**Comment by elrayle** [comment] 2019-11-04 18:11
@kirkhess RE: obsolete - are the obsolete codes tagged as obsolete in any way?

**Comment by elrayle** [comment] 2020-05-12 18:38
Closing... added to Sinopia using list component in PR https://github.com/LD4P/sinopia_editor/pull/1505

**Comment by sfolsom** [comment] 2020-10-21 21:09
The issues above seem to have been resolved by LC, so I'm reopening this. It would be good to add this back to the queue. https://id.loc.gov/vocabulary/organizations.html

Indexing requirements can be fund here: https://docs.google.com/spreadsheets/d/1rPvEoP9iYNkxJ0eWC8gXe3ci7e6mhW0da59xkGhadi0/edit#gid=71593845

I can write tests when the yaml file is available.

**Comment by sfolsom** [comment] 2021-09-01 13:23
Is it possible to try to close this one? I think we stopped at creating the YAML file.

**Comment by elrayle** [comment] 2021-09-01 15:23
A few observations from reviewing the bulk downloads at the end of page https://id.loc.gov/vocabulary/organizations.html 

* There are download options for skos or mads, but not both together
* Downloading any format results in two files (e.g. organizations.ttl.skos, vocabularyorganizations.ttl.skos)
* The first entry in both files appear to be the same for the ttl version.  I didn't check any of the others.
* Doing `diff organizations.ttl.skos vocabularyorganizations.ttl.skos` does show diffs, so the files aren't identical.

Is there a reason we want to put this in YAML instead of ingesting into the cache?

**Comment by sfolsom** [comment] 2021-09-01 15:29
Sorry for the confusion. We want to cache and index; the YAML file is for the tests.

**Comment by elrayle** [comment] 2021-09-22 19:29
@eichmann bulk download available at https://id.loc.gov/vocabulary/organizations.html

**Comment by eichmann** [comment] 2021-12-15 22:24
We're up and running in cache:
loc_cultural_organizations_batch.jsp and loc_cultural_organizations_lookup.jsp

**Comment by elrayle** [comment] 2022-04-27 19:16
This query works in QA demonstrating that this issue complete.

https://lookup.ld4l.org/authorities/search/linked_data/loccultural_organizations_ld4l_cache?q=smithsonian&maxRecords=4&context=false

**Closed by elrayle** 2022-04-27 19:16 UTC
